name: build

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: checkout package
        uses: actions/checkout@v3
      - name: setup jdk
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'adopt'
      - name: build
        run: mvn --batch-mode --update-snapshots test
      - name: coverage badhe
        uses: cicirello/jacoco-badge-generator@v2
        with:
          generate-branches-badge: true